### ISSUE TITLE
Missing frames_df_10_19_19.csv and pretrained models

### ISSUE THREAD

**Issue by ligengen** [amirbar/speech2gesture#22]
Hi, thank you so much for your work!

I met some problems reproducing your work. Many pre-trained models are missing in google drive. All of them do not have `data-00000-of-00001` files. Some of them only contain a `.index` file. https://drive.google.com/drive/folders/1yBJur-FjtMGNZTKKvEY5WuppG2yp2SJO

Then I try to retrain your model. But `frames_df_10_19_19.csv` is missing in google drive. 

It is really strange that someone could reproduce them in 2021. So did you remove those files from the drive?

Looking forward to your reply!

https://drive.google.com/drive/folders/1qvvnfGwas8DUBrwD4DoBnvj8anjSLldZ

**Comment by shinydinosaur** [comment]
Hello!

Thank you so much for pointing this out! Our google drive got corrupted and we lost the data stored there. Apologies for the long response time - it took me some time to locate the originals. I have now restored it and you should be able to find both the csv file and a zip containing all the latest trained models. Your note is much appreciated as we would not have known otherwise that the data was missing.

Please let me know if you are still experiencing any problems accessing the data.

Best,
Shiry
